#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuta Sakusabe <s23c1062mq@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random

def role(a):
    TANK = ["D.VA", "ウィンストン", "オリーサ", "ザリア", "シグマ", "ジャンカークイーン", "ドゥームフィスト", "マウガ", "ラインハルト", "ラマットラ", "レッキングボール", "ロードホッグ"]
    DPS = ["アッシュ", "ウィドウメイカー", "エコー", "キャスディ", "ゲンジ", "シンメトラ", "ジャンクラット", "ソジョーン", "ソルジャー76", "ソンブラ", "トレーサー", "トールビョーン", "ハンゾー", "バスティオン", "ファラ", "ベンチャー", "メイ", "リーパー"]
    SUPPORT = ["アナ", "イラリー", "キリコ", "ジュノ", "ゼニヤッタ", "バティスト", "ブリギッテ", "マーシー", "モイラ", "ライフウィーバー", "ルシオ"]

    if a in ("tank"):
        return (f"{random.choice(TANK)}")
    elif a in ("dps"):
        return (f"{random.choice(DPS)}")
    elif a in ("support"):
        return (f"{random.choice(SUPPORT)}")
    else:
       return "無効な入力です"

if len(sys.argv) != 2:
    print("無効な入力です")
    print("入力例：./hero_select tank")
    sys.exit(1)

user_input = sys.argv[1].strip().lower()


result = role(user_input)
print(result)
