#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuta Sakusabe <s23c1062mq@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random

def role(a):
    TANK = ["D.VA", "ウィンストン", "オリーサ", "ザリア", "シグマ", "ジャンカークイーン", "ドゥームフィスト", "マウガ", "ラインハルト", "ラマットラ", "レッキングボール", "ロードホッグ"]
    DPS = ["アッシュ", "ウィドウメイカー", "エコー", "キャスディ", "ゲンジ", "シンメトラ", "ジャンクラット", "ソジョーン", "ソルジャー76", "ソンブラ", "トレーサー", "トールビョーン", "ハンゾー", "バスティオン", "ファラ", "ベンチャー", "メイ", "リーパー"]
    SUPPORT = ["アナ", "イラリー", "キリコ", "ジュノ", "ゼニヤッタ", "バティスト", "ブリギッテ", "マーシー", "モイラ", "ライフウィーバー", "ルシオ"]

    if a == "tank":
        return random.choice(TANK)
    elif a == "dps":
        return random.choice(DPS)
    elif a == "support":
        return random.choice(SUPPORT)
    else:
       return None


for line in sys.stdin:
    user_input = line.strip().lower()
    result = role(user_input)
    if result != None:
        print(result)
        sys.exit(0)
    else:
        print("無効な入力です")
        sys.exit(1)
